#! /bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s

/sbin/hwclock -s

syslogd

# install additional modules
MODULE_PATH=/lib/modules/`uname -r`
modprobe exynos_fimc_is
modprobe ov5640

